Added speed and cadence sensors
incyclist/ant-plus pull request #15
Opened 2023-02-03 18:55 UTC by antoniodgonzalez

2023-02-04 09:59 UTC, gdoumen requested changes
Some of the constants are not set correctly. 

This might lead to a 'drift', i.e. the sensor might receive the values at the beginning, but might run into timing issues later

2023-02-04 09:59 UTC, gdoumen commented on src/sensors/cadence-sensors.ts
> +const PERIOD = 8182;
According to the spec, PERIOD should be 8102

The weird thing is that in the original implementation (wich was forked into gdoumen/ant-plus) the value i set to 8086

2023-02-04 09:59 UTC, gdoumen commented on src/sensors/speed-sensors.ts
> +const PERIOD = 8182;
According to the spec, PERIOD should be 8118

The weird thing is that in the original implementation (wich was forked into gdoumen/ant-plus) the value is set to 8086

2023-02-04 09:59 UTC, gdoumen commented on src/sensors/speed-sensors.ts
> +    wheelCircumference: number = 2.118; //This is my 700c wheel, just using as default
maybe we should move the member declaration to the top of the class and introduce a constant DEFAULT_WHEEL_CIRCUMFERECE=2.118  next to the other constants

2023-02-04 09:59 UTC, gdoumen commented on src/sensors/speed-cadence-sensors.ts
> +const PROFILE = 'S&C';
I know that I told you to stick to the names in the ANT+ specs. However, in this particular case, I was asking myself if we could not end up in encoding issues with the & sign.

So would could consider to use SCS (**S**peed and **C**adence **S**ensor)

2023-02-04 09:59 UTC, gdoumen commented on src/sensors/speed-cadence-sensors.ts
> +const PERIOD = 8182;
According to the spec, PERIOD is 8086

2023-02-04 12:36 UTC, antoniodgonzalez commented on src/sensors/speed-cadence-sensors.ts
> +const PROFILE = 'S&C';
I'm not fully convinced with using the Sensor suffix for consistence reasong, as is not used by other names. But I cannot find a better name.

2023-02-05 08:49 UTC, gdoumen approved these changes

2023-02-05 08:51 UTC, gdoumen requested changes

2023-02-05 08:51 UTC, gdoumen commented on src/sensors/speed-cadence-sensors.ts
>  const PROFILE = 'S&C';
you still have left "S&C" in here, but in the samples you were using "SC"

2023-02-05 08:53 UTC, gdoumen approved these changes

2023-02-05 09:53 UTC, merged